server:
  port: 8088
  servlet:
    context-path: /xxl

#logging:
#  level:
#    org.springframework.web: TRACE

spring:
# ===================================
# 工作流
# ===================================
  activiti:
    # 数据库执行策略,true 会对数据库中所有的表进行更新,没有就会自动创建
    database-schema-update: true
    #保存历史数据级别设置为full最高级别，便于历史数据的追溯
    history-level: full
    # 检测身份信息表是否存在 默认值即可
    db-identity-used: false

springfox:
  documentation:
    enabled: true

