server:
  port: 8081
    context-path: /xxl
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID #防止Cookie冲突，冲突会导致登录验证不通过
xxl-oauth2-jwt-url: http://localhost:8088/xxl
spring:
  application:
    name: oauth2-sso
security:
  oauth2: #与xxl-oauth2-jwt对应的配置
    client:
      client-id: admin
      client-secret: admin123456
      user-authorization-uri: ${xxl-oauth2-jwt-url}/xxl/oauth/authorize
      access-token-uri: ${xxl-oauth2-jwt-url}/xxl/oauth/token
    resource:
      jwt:
        key-uri: ${xxl-oauth2-jwt-url}/xxl/oauth/token_key
