server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xxl_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: xxl
    password: helloxxl
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: xxl-redis-ps # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

# 自定义redis key
redis:
  database: xxl
  key:
    authCode: 'ums:authCode'
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

secure:
  ignored:
    urls:
      - /
      - /swagger-ui/
      - /*.html
      - /favicon.ico
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /swagger-resources/**
      - /v2/api-docs/**
      - /actuator/**