server:
  port: 8080
  servlet:
    context-path: /


spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/xxl-springsecuritylearning?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: xxl
    password: helloxxl
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 1
      max-active: 20
      max-wait: 60000